name: Build English For Us APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Android Folder
        run: |
          rm -rf android
          flutter create . --platforms android

      - name: Fix Deprecated Proguard in Cache
        run: |
          find ~/.pub-cache/hosted/pub.dev -name "build.gradle" -exec sed -i 's/getDefaultProguardFile(\x27proguard-android.txt\x27)/getDefaultProguardFile(\x27proguard-android-optimize.txt\x27)/g' {} +
          find ~/.pub-cache/hosted/pub.dev -name "build.gradle" -exec sed -i 's/getDefaultProguardFile("proguard-android.txt")/getDefaultProguardFile("proguard-android-optimize.txt")/g' {} +

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: English-For-Us-APK
          path: build/app/outputs/flutter-apk/app-release.apk